@class BioLog, NSString, CMAttitude, STMediaStatusDomainPublisher, CMWakeGestureManager, CMMotionManager, NSObject, CMDeviceOrientationManager, NSMutableData, PearlCoreAnalytics;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface BiometricKitXPCServerPearl : BiometricKitXPCServer <CMWakeGestureDelegate, NSXPCListenerDelegate> {
    unsigned int _services;
    unsigned int _connect;
    unsigned int _status;
    unsigned short _commProtocolVersion;
    int _peakPowerPressureLevelNtfToken;
    BOOL _peakPowerPressureLevelNtfTokenValid;
    long long _pearlDeviceState;
    BioLog *_log;
    BOOL _loggingOnRelease;
    NSObject<OS_dispatch_queue> *_sharedMemoryTransferQueue;
    NSObject<OS_dispatch_queue> *_loggingDispatchQueue;
    BOOL _logSequenceDebug;
    BOOL _logIdentityRemoval;
    PearlCoreAnalytics *_analytics;
    NSObject<OS_dispatch_queue> *_analyticsDispatchQueue;
    CMWakeGestureManager *_wakeGestureManager;
    CMDeviceOrientationManager *_orientationManager;
    CMMotionManager *_motionManager;
    NSObject<OS_dispatch_queue> *_motionDispatchQueue;
    BOOL _orientationManagerRunning;
    unsigned long long _lastDeviceOrientation;
    CMAttitude *_lastDeviceAttitude;
    struct { double x; double y; double z; } _lastRotationRate;
    struct { double x; double y; double z; } _lastUserAcceleration;
    struct { double x; double y; double z; } _lastGravity;
    NSObject<OS_dispatch_source> *_sigTERMDispatchSource;
    BOOL _coachingHintsEnabled;
    NSMutableData *_performCommandBufferData;
    BOOL _performCommandBufferInUse;
    struct { unsigned int val[8]; } _localToken;
    STMediaStatusDomainPublisher *_mediaStatusDomainPublisher;
    unsigned char _unlockWithGlassesFailCount;
    BOOL _unlockWithGlassesFailed;
    BOOL _glassesBannerDisplayed;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (unsigned int)getChipID;
+ (void)reportPearlIssue;
+ (unsigned int)getDeviceTreeProperty:(id)a0 fromPath:(id)a1;
+ (unsigned int)getSkipBane;
+ (unsigned int)getBoardID;
+ (void)reportPearlInterlock:(BOOL)a0;
+ (void)reportPearlHardwarePass:(BOOL)a0 fallbackAction:(id /* block */)a1;
+ (id)getSHA384FromData:(id)a0;

- (int)getSPRLInfo:(struct { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; } *)a0;
- (int)pauseFaceDetectTimer:(BOOL)a0 withClient:(id)a1;
- (void)wakeGestureManager:(id)a0 didUpdateWakeGesture:(long long)a1;
- (void)matchResult:(id)a0 withTimestamp:(unsigned long long)a1;
- (int)serviceStatus:(unsigned int)a0 version:(unsigned int)a1 ordinal:(unsigned long long)a2 data:(id)a3 timestamp:(unsigned long long)a4;
- (int)performRemoveIdentityCommand:(struct { unsigned int x0; unsigned char x1[16]; } *)a0;
- (int)startNewMatchAttemptWithClient:(id)a0;
- (int)performForceBioLockoutCommand:(unsigned int)a0;
- (int)performGetSystemProtectedConfigCommand:(id *)a0;
- (unsigned long long)deviceOrientation;
- (int)performGetTemplatesValidityCommand:(unsigned int)a0 isValid:(BOOL *)a1;
- (int)performDisplayStatusChangedCommand:(BOOL)a0;
- (int)performConfirmSaveCatacombCommand:(id)a0;
- (int)completeEnrollmentWithClient:(id)a0;
- (unsigned int)serviceConnect;
- (int)initPresenceDetectOperation:(id)a0 options:(id)a1 client:(id)a2;
- (int)performGetLastMatchEventCommand:(struct { unsigned long long x0; unsigned char x1; struct { unsigned int x0; unsigned char x1[16]; } x2; } *)a0;
- (int)performGetCatacombUUIDCommand:(unsigned int)a0 outUUID:(id *)a1;
- (int)performDropUnlockTokenCommand;
- (int)updatePropertiesOfIdentities;
- (int)getBioLockoutState:(long long *)a0 forUser:(unsigned int)a1 withClient:(id)a2;
- (id)init;
- (id)getRomeoSerialNumberFDR;
- (int)loadCatacombForComponent:(id)a0;
- (int)initializeEngine;
- (int)performSetProtectedConfigCommand:(unsigned int)a0 cfg:(id)a1 authData:(struct { unsigned int x0; unsigned int x1; unsigned char x2[32]; } *)a2;
- (int)performGetBiometrickitdInfoCommand:(struct { unsigned int x0; unsigned int x1; unsigned int x2; unsigned long long x3; unsigned char x4; unsigned char x5; unsigned char x6; } *)a0;
- (int)enableMatchAutoRetry:(BOOL)a0 withClient:(id)a1;
- (int)performMatchCommand:(id)a0;
- (int)performGetCatacombHashCommand:(unsigned int)a0 outHash:(id *)a1;
- (void)statusMessage:(unsigned int)a0 withData:(id)a1 timestamp:(unsigned long long)a2;
- (int)performNoCatacombCommand:(unsigned int)a0;
- (int)loadPCECalibrationOverride:(id)a0;
- (int)performRequestMaxIdentityCountCommand:(unsigned int *)a0;
- (int)sendFDRDataCheckResult:(int)a0;
- (int)performCompleteSaveCatacombCommand:(id)a0 outBuffer:(id)a1;
- (void)enrollResult:(id)a0 withTimestamp:(unsigned long long)a1;
- (int)performGetSKSLockStateCommand:(unsigned int)a0 outState:(unsigned int *)a1;
- (void)updateCombinedSequenceMode;
- (int)restoreAndSyncTemplates;
- (void)serviceMatch:(unsigned int)a0;
- (int)performGetCatacombStateCommand:(id)a0;
- (int)performGetFreeIdentityCountCommand:(unsigned int)a0 outCount:(unsigned int *)a1;
- (int)loadFDRClassCommand:(int)a0 withClass:(int)a1 withData:(id)a2 isAlternative:(BOOL)a3;
- (id)createEnrollOperation;
- (int)initMatchOperation:(id)a0 filter:(id)a1 options:(id)a2 client:(id)a3;
- (int)performSetSystemProtectedConfigCommand:(id)a0 authData:(struct { unsigned int x0; unsigned int x1; unsigned char x2[32]; } *)a1;
- (struct { double x0; double x1; double x2; })deviceRotationRate;
- (int)updateIdentity:(id)a0 withOptions:(id)a1 withClient:(id)a2;
- (int)suspendEnrollment:(BOOL)a0 withClient:(id)a1;
- (int)isPeriocularEnrollmentSupported:(BOOL *)a0 withClient:(id)a1;
- (int)performEnrollCommand:(id)a0;
- (int)performPresenceDetectCommand:(id)a0;
- (int)saveTemplateListAfterTemplateUpdate;
- (int)performGetDeviceHardwareStateCommand:(unsigned int *)a0;
- (void)handleSharedMemoryTransfer:(unsigned int)a0 withHeader:(id)a1 data:(id)a2;
- (long long)getDeviceStateWithClient:(id)a0;
- (int)performRequestMessageDataCommand:(unsigned long long)a0 size:(unsigned long long)a1 outData:(id *)a2;
- (int)getPeriocularMatchStateForUser:(unsigned int)a0 state:(long long *)a1 withClient:(id)a2;
- (int)setTemplate:(id)a0 forIdentity:(id)a1 withClient:(id)a2;
- (void)updateCoachingHintsEnabled;
- (int)removePeriocularTemplatesWithOptions:(id)a0 withClient:(id)a1;
- (int)performCancelCommand;
- (int)performPrepareSaveCatacombCommand:(id)a0 outDataSize:(unsigned int *)a1;
- (int)queryIdentityMigrationFailureForUser:(unsigned int)a0 failed:(BOOL *)a1 clear:(BOOL)a2 withClient:(id)a3;
- (int)initEnrollOperation:(id)a0 biometricType:(int)a1 userID:(unsigned int)a2 options:(id)a3 client:(id)a4;
- (id)createPresenceDetectOperation;
- (void)faceDetectMessage:(unsigned int)a0 info:(struct { unsigned char x0; unsigned short x1; unsigned short x2; unsigned short x3; unsigned short x4; unsigned int x5; float x6; float x7; float x8; unsigned int x9; } *)a1;
- (int)performRemoveUserDataCommand:(unsigned int)a0;
- (int)initAutoBugCapture;
- (int)performGetIdentitiesListCommand:(unsigned int)a0 outBuffer:(id)a1;
- (void)enrollUpdate:(id)a0 withTimestamp:(unsigned long long)a1;
- (id)getFDRClassFromFDR:(id)a0;
- (id)createMatchOperation;
- (int)performLoadCatacombCommand:(id)a0 inData:(id)a1;
- (int)removeIdentity:(id)a0 withOptions:(id)a1 withClient:(id)a2;
- (int)performGetProtectedConfigCommand:(unsigned int)a0 outSetCfg:(id *)a1 outEffectiveCfg:(id *)a2;
- (void)enrollFeedback:(id)a0 withTimestamp:(unsigned long long)a1;
- (void)firstUnlockCallback;
- (int)loadSavageFWCertificate;
- (BOOL)hasFDREntitlement;
- (void)logRemoveIdentity:(id)a0 withClient:(id)a1;
- (void)registerForLiftToWakeNotifications:(BOOL)a0;
- (int)verifyProjectorSerialNumber;
- (void)updateAutoRetryMode;
- (void)donateBiomeEvent:(id)a0;
- (int)verifyRomeoSerialNumberAgainstFDR;
- (void)updateLoggingState;
- (int)verifyDisplayTrust;
- (id)getDisplayTrustStatusAttempt;
- (int)sendDCNKernelsCheckResult:(int)a0;
- (id)getProjectorSerialNumberIORegAttempt;
- (void).cxx_destruct;
- (struct { double x0; double x1; double x2; })deviceGravity;
- (void)matchEventMessage:(struct { unsigned long long x0; unsigned char x1; struct { unsigned int x0; unsigned char x1[16]; } x2; } *)a0;
- (id)getFDRClassFromFile:(id)a0;
- (int)sendDisplayCheckResult:(int)a0;
- (id)detailsForFaceDetectInfo:(const struct { unsigned char x0; unsigned short x1; unsigned short x2; unsigned short x3; unsigned short x4; unsigned int x5; float x6; float x7; float x8; unsigned int x9; } *)a0;
- (BOOL)hasManifestEntitlement:(unsigned int)a0;
- (int)sendRomeoSNCheckResult:(int)a0;
- (id)deviceAttitude;
- (int)loadDCNKernels;
- (int)queryGuadalupeSerialNumberFDR:(id *)a0;
- (void)logSequenceDebugWithContext:(struct { unsigned long long x0; unsigned long long x1; struct { unsigned long long x0; unsigned short x1; unsigned char x2; } x2; } *)a0;
- (int)loadFDRCalibrationData:(BOOL)a0;
- (void)dealloc;
- (struct { double x0; double x1; double x2; })deviceUserAcceleration;
- (id)classStringForEnum:(int)a0;
- (void)checkBioLogConsent;
- (void)analyticsKernelMessage:(id)a0;
- (void)logKernelMessage:(id)a0;
- (int)sendSelfCheckResult:(struct { int x0; int x1; int x2; int x3; int x4; } *)a0;
- (int)performCommand:(unsigned short)a0 inValue:(unsigned short)a1 inData:(const void *)a2 inSize:(unsigned long long)a3 outData:(char *)a4 outSize:(unsigned long long *)a5;
- (id)pathForAlternateFDRClass:(id)a0;
- (int)performCommand:(unsigned short)a0 version:(unsigned short)a1 inValue:(unsigned short)a2 inData:(const void *)a3 inSize:(unsigned long long)a4 outData:(char *)a5 outSize:(unsigned long long *)a6;
- (int)queryPeriocularMigrationState:(BOOL *)a0 clear:(BOOL)a1;
- (id)getProjectorSerialNumberIOReg;
- (void)loadCalibrationData;
- (id)filenameForSavageCertType:(id)a0;
- (void)updateEntitlementOverrideFlags;
- (int)verifyGuadalupeSerialNumberAgainstFDR;
- (int)getCommProtocolVersion;

@end
